spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/MyTutorAlex26?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: "!VarnaVarna35!"
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#  za da se initializaira SQL tablicata s dannite ot data.sql trqbva ni samo pri pyrvoto importirane posle zakomentirame
#  sql:
#    init:
#      mode: always

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

  #Settings to connect to the REST API         REST_1
  #REST_2  FOREX_API_KEY under environment variables
forex:
  api:
      key: ${FOREX_API_KEY:}   # the key is my unique ID that I got after the registration. I have to pay if I wat it after 1000 times
      url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
      base: "USD"

      # the key is configuration as an environment variable under "Edit configuration"

#ErrorHandling -> Foe example better error page if we try localhost:8080/hhhh
#server:
#  error:
#    path: /Alex

